# Generated by Django 2.0.7 on 2018-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='propiedad_principal',
            field=models.CharField(choices=[('p', 'Proteina'), ('c', 'Carbohidrato'), ('m', 'Mineral'), ('g', 'Grano'), ('ci', 'Citrico'), ('d', 'Dulce'), ('n', 'Neutro'), ('l', 'Lacteo')], help_text='Caracteristica del alimento', max_length=1),
        ),
    ]
