# Generated by Django 2.0.7 on 2018-07-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180710_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(blank=True, max_length=10, null=True)),
                ('preparation', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe', models.CharField(max_length=100, verbose_name='Receta')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_quantity_set', to='search.Ingrediente')),
            ],
            options={
                'verbose_name_plural': 'recipe ingredient quantities',
                'default_related_name': 'ingredient_quantity_set',
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('recipe', models.CharField(max_length=100, verbose_name='Receta')),
            ],
            options={
                'default_related_name': 'recipe_step_set',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=60, unique=True)),
                ('short_name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['long_name'],
            },
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='ingrediente',
            new_name='ingredientes',
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_quantity_set', to='search.Unit'),
        ),
    ]
