# Generated by Django 2.0.7 on 2018-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180717_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='id',
            field=models.AutoField(default=1, help_text='ID único para esta receta particular en toda la biblioteca', primary_key=True, serialize=False),
        ),
    ]
