# Generated by Django 2.0.7 on 2018-07-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20180717_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='tipo',
        ),
    ]
