# Generated by Django 2.0.7 on 2018-07-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_receta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='excepciones',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='propiedad_principal',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='propiedad_secundaria',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='restricciones',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='subproducto',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='reino',
            field=models.CharField(max_length=200),
        ),
    ]
