# Generated by Django 2.0.7 on 2018-07-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20180726_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='reino',
            new_name='sustituiblex',
        ),
    ]
