# Generated by Django 2.0.7 on 2018-08-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20180726_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(help_text='Ingrese la preparacion', max_length=5000),
        ),
    ]
